apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-search-poc
  labels:
    app.kubernetes.io/name: document-search-poc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: document-search-poc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: document-search-poc
    spec:
      containers:
        - name: document-search-poc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always