
replicaCount: 1

image:
  repository: ghcr.io/joshualarouche/document-search-poc
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
